### PR TITLE
Add file tester

### PR DESCRIPTION
**Pull request by alpiccioni**
Should be useful for onboarding to package managers. Does non-trivial testing on the files, but doesn't actually launch fzf.

### CODE REVIEW

**Comment by bartekpacia** [comment]
How should I use it? That's what I'm getting:


```
$ pwd
/Users/bartek/dev/random/purr
$ ./tests/tester/validate_files.sh -p ./out/purr -a ./tests/mocks/adb_mock.sh -X
purr
[-q: Sets the default query]
[-i: Disables the instruction header]
[-a: Set custom adb parameters as a string]
[-f: Set custom fzf parameters as a string]
[-v: Get version number]
[-V: Get version of all dependencies]
grep: /tmp/purr.xTOgMk9aTO/serial-cache.purr: No such file or directory
```

**Comment by alpiccioni** [comment]
```
out/file_tester -a out/adb_mock -p out/purr
```

Works for me. Let me know it's being problematic.

**Comment by bartekpacia** [comment]
It works!
Thanks for all your amazing work on this.

**Comment by bartekpacia** [comment]
You can merge this and release 2.0.2 and I'll use that test in the homebrew formula.

**Comment by alpiccioni** [comment]
Merged and released. Thanks!

**Pull request closed without merging**
